-- ZABELLA / SUPABASE - configuração para TESTE

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  sizes jsonb not null default '[]'::jsonb,
  image_url text,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id bigint primary key,
  whatsapp text not null default '',
  instagram text not null default '',
  email text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.store_settings(id,whatsapp,instagram,email)
values(1,'5511999999999','zabella','contato@zabella.com')
on conflict(id) do nothing;

alter table public.products enable row level security;
alter table public.store_settings enable row level security;

create policy "products_select_test" on public.products
for select to anon, authenticated using (true);

create policy "products_insert_test" on public.products
for insert to anon, authenticated with check (true);

create policy "products_update_test" on public.products
for update to anon, authenticated using (true) with check (true);

create policy "products_delete_test" on public.products
for delete to anon, authenticated using (true);

create policy "settings_select_test" on public.store_settings
for select to anon, authenticated using (true);

create policy "settings_insert_test" on public.store_settings
for insert to anon, authenticated with check (true);

create policy "settings_update_test" on public.store_settings
for update to anon, authenticated using (true) with check (true);

-- No Storage, crie manualmente um bucket público chamado:
-- products
